### ISSUE TITLE
Please clarify “users’ fonts”

### ISSUE THREAD

**Issue by Pan70** [kobolabs/epub-spec#15]
Could you clarify this part so that we know if it is possible to use default/user fonts in publisher’s CSS (font-stacks)? And if it is, could you list the names we can use?

I’ve been trying to use eInk fonts such as Malabar or Amasis for weeks, using alternative names like MalabareText and "Malabar eText", but the stack falls back to Georgia (serif) or Avenir (sans-serif) on my Kobo Mini.

Also, on my Kobo Mini, sans-serif fonts don’t ship with italic styles and are replaced with bold, which creates extra customer care as people think we don’t know how to typeset….

**Comment by bdugas** [comment]
Hello, can you send a sample file or link to that file to renderingissues@kobo.com? The short answer is likely that what your attempting can't be done on Kobo eInk devices but we can confirm and pass on more feedback if we can see the file you are using.

**Comment by bdugas** [comment]
We've updated this section - https://github.com/kobolabs/epub-spec#embedded-fonts-can-be-selected-by-users - to advise against referencing fonts that are not embedded. It may still be possible to reference the fonts that we have built into each device but we do not believe that this practice would result in content that produces a consistent reading experience across our apps and devices.
