### ISSUE TITLE
Page Break Clarification

### ISSUE THREAD

**Issue by tooolbox** [kobolabs/epub-spec#18]
In your section on inline styling, you give some examples.
`````
HTML:
<p class="normal text">Sample text before page break</p>
<p class="normal text2">Sample text after page break</p>
CSS:
@normal text { footer {page-break-after: always;} }
`````
vs.
`````
HTML:
<p class="normal text">Sample text before page break</p>
<code><div style="page-break-before:always;"></div>
<p class="normal text2">Sample text after page break</p>
`````
What is this? --> `@normal text { footer {...} }`  Some kind of media query?  Do you mean something like this:
`````
HTML:
<p class="normal-text">Sample text before page break</p>
<p class="normal-text2">Sample text after page break</p>
CSS:
p.normal-text { page-break-after: always; }
`````

I'm asking, because I've found that it doesn't seem to be creating page breaks on my ebook, after I began using the Kobo Webkit by changing the extension to `.kepub.epub`

**Comment by wareid** [comment]
Thanks for catching this! I'm updating the example now, it's just a bit of example code (admittedly a bit confusing). We will be testing out page-break CSS and updating the spec on how we handle it across platforms. We will update the spec with the results of that test!

**Comment by daniel-j** [comment]
@wareid what is the status on the testing of page-break CSS? I have noticed it renders correctly in normal epubs but not in `.kepub.epub` (different renderer)

**Comment by tooolbox** [comment]
@wareid I'm interested in this too.  I haven't done anything with Kobo since I realized that I didn't know how to induce a page-break on your custom rendering engine (which is in use on at least half of your platforms, from what I could tell).

**Comment by bdugas** [comment]
@daniel-j @tooolbox results are now in the CSS section https://github.com/kobolabs/epub-spec#css
We are looking into improving support across for apps but for now at least our level of support is documented.

**Comment by tooolbox** [comment]
@bdugas I appreciate the documentation and transparency on this, very helpful.

Unfortunately, the ability to do a page break is vital for my books.  I can't put them on a platform where, depending on which device the reader has, pages jam together which need to be separate.

I'm looking forward to Kobo having full support for this across all their devices!

**Comment by bdugas** [comment]
@tooolbox can you email us at kobo-renderingissues@mail.rakuten.com with some rough numbers - how many books, what other platforms you're selling on? I'll attach it to our internal tickets and it will help us demonstrate the value. I'm sure you're not the only content creator to whom page breaks are vitally important to the content but the example will be useful.

**Comment by randbrittain** [comment]
This is definitely a big issue for me, as well, and it's still a problem five years later. I write ePub versions of role-playing game manuals, and being able to do page-breaks is critical for having lots of separable headings without also having 1000 separate XHTML files inside the EPUB.
