### ISSUE TITLE
How to disable(and handle) the pop-up footnote on e-ink devices?

### ISSUE THREAD

**Issue by yasteora** [kobolabs/epub-spec#24]
1. when I did not use epub:type:"refnote" ("footnote", "rearnote",etc) on my tags, but  kobo consider the some of  hyperlinks as  footnotes.

2. when i use the pop-up fearture, but the pop-up box sometimes would show too more content below the the  footnotes.

**Comment by bdugas** [comment]
Sorry for the delay but we've looked into it and updated the section on footnotes/endnotes: https://github.com/kobolabs/epub-spec/blob/master/README.md#footnotesendnotes-are-fully-supported-across-kobo-platforms
In short, if you want to prevent the popups just make sure you are not fulfilling the criteria we've listed ie. link to whole chapters, link to elements that are longer than 5000 characters or link to elements that occur earlier in the file.
