### ISSUE TITLE
Add section about navigator.epubReadingSystem

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#26]
If I'm not mistaken, there’s no mention of `navigator.epubReadingSystem` in the spec. Now, it can be useful sometimes → http://epubzone.org/news/epub-3-and-interactivity#_the_epub_3_epubreadingsystem_object

So basically, we don’t know whether it’s implemented or not if we don’t test or check http://epubtest.org/testsuite/epub3/feature/epub-reading-system/, but maybe it’s been implemented since?

**Comment by bdugas** [comment]
I tested on all our current apps and we unfortunately still only support it on Desktop and eInk. I've updated our section on JavaScript accordingly: https://github.com/kobolabs/epub-spec#javascript-support
