### ISSUE TITLE
Add and clarify iframe

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#27]
If I'm not mistaken, there’s nothing about iframe in the spec. 

As far as I know, it is supported in iOS but with a few caveats e.g. the iframe is automatically opened in Safari if it’s an external ressource, a case for which it would definitely be cool to have `navigator.epubReadingSystem` (see issue #26) because I consider this “terrible-UX-borderline-to-bug” from the user’s point of view.

Haven’t tested iframes with internal ressources yet but this might become the new new hype since [kids learnt some months ago you can use online services to create “widgets” you can then implement as iframes in your ebook file](https://storify.com/LauraB7/interactive-quizzes-puzzles-and-games-in-fixed-lay).

**Comment by JayPanoz** [comment]
FYI, works OK in Android so this is an iOS-specific issue.

**Comment by bdugas** [comment]
@JayPanoz we've logged a story with our iOS team and will hopefully have iframe support included in a future release. If you have any test files you want to pass along we'd be happy to use them to verify acceptance criteria has been met.
