### ISSUE TITLE
[Kobo Android] You might want to be careful with console.log

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#29]
I'm currently building a script for debug tools, which is binding the console to a virtual console in the DOM. In other words, it injects **every** log, error, etc. into the DOM, even system’s.

While testing this in Kobo Android, got access to app’s logs (two last lines in the screenshot).

![crsnhgdwcaic1ff](https://cloud.githubusercontent.com/assets/12599652/18311905/484a81aa-7507-11e6-816a-df488b589b8a.jpg)

“Why reporting this” you may ask… Depends on what you're logging, obviously, but could also turn into a security issue if some critical data is “console.logged”.

**Comment by bdugas** [comment]
Thanks @JayPanoz we've looked into it and this is not a significant security issue but we will likely remove it from a future release regardless.

**Comment by JayPanoz** [comment]
👍

I'd found nothing “critical” but prevention is better than cure, obviously.
