### ISSUE TITLE
[Kobo Android] Missing settings

### ISSUE THREAD

**Issue by JayPanoz** [kobolabs/epub-spec#30]
OK so this is kinda weird.

Is this [help page](https://www.kobo.com/help/en-US/article/3310/changing-the-font-size-and-style-while-reading?products=Android) up to date? Cos’ I can’t access those settings on a Honor 5x when using the Android app. 

Pinch to enlarge font-size is working though, but no reading menu nor themes in sight, either when side loading files or downloading from the store.

**Comment by bdugas** [comment]
@JayPanoz this sounds like a known bug that should be fixed for an upcoming release. Which app version are you using? Do the options appear when you view in landscape?

**Comment by JayPanoz** [comment]
OK so v.6.6.16008.

They indeed are available in landscape (sorry about that, given the aspect ratio, I almost never use landscape view and auto-rotate screen is disabled).

![screenshot_2016-09-08-18-15-57](https://cloud.githubusercontent.com/assets/12599652/18357405/34c58a7c-75f1-11e6-9781-4a35ca792187.png)

![screenshot_2016-09-08-18-16-18](https://cloud.githubusercontent.com/assets/12599652/18357407/34e1fc66-75f1-11e6-98dc-bed0355c14fd.png)

Menus are cropped though (nav bar). 

![screenshot_2016-09-08-18-16-28](https://cloud.githubusercontent.com/assets/12599652/18357455/572fa0c0-75f1-11e6-848b-27fbaffbd9cc.png)

**Comment by bdugas** [comment]
Thanks, that is a known bug and has been fixed. It should go out in our next release and only currently occurs on some Android devices.

**Comment by JayPanoz** [comment]
OK thanks, I'll check the next update and report back.
