### ISSUE TITLE
epubtest.org NO LONGER ONLINE

### ISSUE THREAD

**Issue by mdefatima** [kobolabs/epub-spec#37]
When referring to the support grid for SVG, fonts and other matters, epubtest.org is referred to as the place to clear any doubts that should arise. However, epubtest.org is no longer online, so any questions that should arise will remain unresolved.

**Comment by bdugas** [comment]
Our section on SVG has been updated (based on our testing we support SVG on all platforms) and mentions to epubtest.org have been removed. Thanks for bringing this to our attention.
