### ISSUE TITLE
Differing information on SVG support

### ISSUE THREAD

**Issue by jstallent** [kobolabs/epub-spec#39]
One location (https://github.com/kobolabs/epub-spec#image-formatting) in this document says, "but not Scalable Vector Graphics (SVG), which are not supported on all reading platforms."

Another location (https://github.com/kobolabs/epub-spec#scalable-vector-graphics-svg) says, "Text, images and animations in SVG are supported on all Kobo reading platforms (performance on eInk is limited but the animations will function)." 

Please clarify.

**Comment by bdugas** [comment]
The first one was out of date and has been modified. SVG now works on all Kobo platforms.
