### ISSUE TITLE
endnotes/footnotes issue

### ISSUE THREAD

**Issue by spajak** [kobolabs/epub-spec#45]
On my Clara HD reader (latest soft), links to notes don't work:

I have a reference:
```
<a epub:type="noteref" href="przypisy.xhtml#endnote-8-1" class="noteref">*1</a>
```

And a note in przypisy.xhtml:
```
<aside epub:type="endnote" id="endnote-8-1">*1. Francisco López de Gómara, Cortés: The Life of the Conqueror by His Secretary, przeł. i oprac. Lesley Byrd Simpson, Berkeley-Los Angeles 1964, s. 8.</aside>
```

Issue: Touching/clicking anchor link does nothing on my ereader.

**Comment by wareid** [comment]
Hi @spajak! 

Please check the section here on footnotes and endnotes: https://github.com/kobolabs/epub-spec#footnotesendnotes-are-fully-supported-across-kobo-platforms

I don't believe we're supporting epub:type="noteref" but I can run a test to double check that. If you change `noteref` to `footnote` or `endnote` it should work.

**Comment by spajak** [comment]
I see. I was thinking `noteref` is an anchor and `foot(end)note` is the content of a note..

**Comment by wareid** [comment]
Can you retest the file on the device by changing the extension to [file].kepub.epub? 

https://github.com/kobolabs/epub-spec#sideloading-for-testing-purposes

**Comment by spajak** [comment]
Yeap. foot(end)notes are working now. But other thinks are broken.. See [#46](url)

**Comment by rriemann** [comment]
Can you please clarify: `noteref`is generally not supported, but works on iOS devices (https://github.com/kobolabs/epub-spec/issues/8)?

The problem is that pandoc generates all epub3 files with `noteref` references in the next.

**Comment by wareid** [comment]
@rriemann For all endnotes/footnotes? If you could provide an example we can test it, but otherwise the recommendation in the document still stands. 

I would also advise even if something is supported on one platform, it's best to have a solution that's cross-platform.

**Comment by rriemann** [comment]
OK for testing.

So I translated with pandoc the following text:

```md
---
title: Test Title
author: Test Author
date: 22 June 2020
---

Here is some text. [^1] Here is again much more text with some extra footnote. [^2]

[^1]: Footnote 1
[^2]: Footnote 2
```

epub3: [test-epub3.zip](https://github.com/kobolabs/epub-spec/files/4815586/test-epub3.zip)
epub2: [test-epub2.zip](https://github.com/kobolabs/epub-spec/files/4815588/test-epub2.zip)

pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
