### ISSUE TITLE
figcaption on next page issue

### ISSUE THREAD

**Issue by spajak** [kobolabs/epub-spec#48]
Sometimes `<figcaption>` (inside `<figure>` with image), is rendered on the next page, even if there is 50% place below the image. Unfortunately don't know why..

**Comment by spajak** [comment]
Please find my epub 3.2 demo here:
`https://mega.nz/#!oaQ1nIKY!Kzl_hZe4XW16ZjFTiCapoxjmHQ7EEQTa55EZAQL6E7A`
The above work well in Kindle (after kindlegen touch) as well as Calibre viewer. Tested on Clara HD (up to date soft).
Main issues I have are navigation (links), sections and figcaption. Please let me know if you find this demo might be improved.

**Comment by wareid** [comment]
I wasn't able to recreate this issue when tested like this: 

https://github.com/kobolabs/epub-spec#sideloading-for-testing-purposes

**Comment by spajak** [comment]
True. But other thinks are broken now, see #46
