### ISSUE TITLE
Valid (epubcheck 4.2.2 + Ace by Daisy 1.1.2) ebook rejected: "Undeclared prefix: 'a11y'"

### ISSUE THREAD

**Issue by AudreyLBE** [kobolabs/epub-spec#56]
A client has come back to me because a book I made has been rejected by Kobo with the error message
"OEBPS/content.opf(26,64): Undeclared prefix: 'a11y'."

The book is a valid epub3 (epubcheck 4.2.2 + Ace by Daisy 1.1.2), the same one referenced in this other report: https://github.com/kobolabs/epub-spec/issues/55 (isbn 978-2-490431-03-8 title "La Famille de l’antiquaire ou la belle-mère et la bru").

How can this be resolved?

**Comment by sflaming** [comment]
Hi AudreyLBE, could you please start a ticket by sending us an email?
renderingissues@kobocontentoperations.zendesk.com
Thank you!
